import { invoke } from "@tauri-apps/api/core";
import type { AppSnapshotDto, BackupDto, BulkAddDto, ConfigItemDto, DiffSessionDto, DiscoveryCandidateDto, DiscoveryScanDto, FileRevisionDto, GitStatusDto, InstallActionDto, KnowledgeApplicationDto, KnowledgeCatalogDto, MigrationPlanDto, OperationDto, PackageDto, PackageScanDto, PreviewFileDto, RepositoryInspectionDto, RestorePlanDto, RestoreRunDto, TextDocumentDto } from "./bindings";

export const desktopApi = {
  snapshot: () => invoke<AppSnapshotDto>("app_snapshot"),
  inspectRepository: (path: string) =>
    invoke<RepositoryInspectionDto>("repository_inspect", { path }),
  createRepository: (path: string, initializeGit = true) => invoke<RepositoryInspectionDto>("repository_create", { path, initializeGit }),
  cloneRepository: (remote: string, destination: string) => invoke<RepositoryInspectionDto>("repository_clone", { remote, destination }),
  listConfigs: (repository: string) => invoke<ConfigItemDto[]>("config_list", { repository }),
  addConfig: (repository: string, target: string, allowSensitive = false) => invoke<ConfigItemDto>("config_add", { repository, target, allowSensitive }),
  scanConfigurations: (repository: string) => invoke<DiscoveryScanDto>("discovery_scan", { repository }),
  addDiscoveredConfigurations: (repository: string, candidates: DiscoveryCandidateDto[]) => invoke<BulkAddDto>("discovery_add", { repository, candidates }),
  previewConfiguration: (root: string) => invoke<PreviewFileDto[]>("discovery_preview_index", { root }),
  readConfigurationPreview: (root: string, file: string) => invoke<TextDocumentDto>("discovery_preview_read", { root, file }),
  listKnowledge: () => invoke<KnowledgeCatalogDto>("knowledge_list"),
  saveKnowledge: (application: KnowledgeApplicationDto) => invoke<KnowledgeCatalogDto>("knowledge_save", { application }),
  deleteKnowledge: (id: string) => invoke<KnowledgeCatalogDto>("knowledge_delete", { id }),
  removeConfig: (repository: string, itemId: string) => invoke<OperationDto>("config_remove", { repository, itemId }),
  captureConfig: (repository: string, itemId: string) => invoke<OperationDto>("config_capture", { repository, itemId }),
  applyConfig: (repository: string, itemId: string) => invoke<OperationDto>("config_apply", { repository, itemId }),
  openDiff: (repository: string, itemId: string) => invoke<DiffSessionDto>("diff_open", { repository, itemId }),
  diffHistory: (repository: string, itemId: string) => invoke<FileRevisionDto[]>("diff_history", { repository, itemId }),
  openDiffRevision: (repository: string, itemId: string, revision: string) => invoke<TextDocumentDto>("diff_open_revision", { repository, itemId, revision }),
  saveRepositoryText: (repository: string, itemId: string, expectedRevision: string, content: string) => invoke<TextDocumentDto>("diff_save_repository", { repository, itemId, expectedRevision, content }),
  scanPackages: (repository: string) => invoke<PackageScanDto>("packages_scan", { repository }),
  savePackages: (repository: string, packages: PackageDto[]) => invoke<OperationDto>("packages_save", { repository, packages }),
  packagePlan: (repository: string, aurHelper?: string) => invoke<InstallActionDto[]>("packages_plan", { repository, aurHelper }),
  installPackage: (packageInfo: PackageDto, aurHelper?: string) => invoke<OperationDto>("package_install", { package: packageInfo, aurHelper }),
  restorePreflight: (repository: string) => invoke<RestorePlanDto>("restore_preflight", { repository }),
  migrationPreflight: (repository: string, aurHelper?: string) => invoke<MigrationPlanDto>("migration_preflight", { repository, aurHelper }),
  executeRestore: (repository: string, planId: string, selectedIds: string[]) => invoke<RestoreRunDto>("restore_execute", { repository, planId, selectedIds }),
  incompleteRestores: (repository: string) => invoke<RestoreRunDto[]>("restore_incomplete", { repository }),
  recoverRestore: (repository: string, runId: string) => invoke<RestoreRunDto>("restore_recover", { repository, runId }),
  keepCurrentRestore: (repository: string, runId: string) => invoke<RestoreRunDto>("restore_keep_current", { repository, runId }),
  gitStatus: (repository: string) => invoke<GitStatusDto>("git_status", { repository }),
  gitCommit: (repository: string, message: string) => invoke<GitStatusDto>("git_commit", { repository, message }),
  gitFetch: (repository: string) => invoke<GitStatusDto>("git_fetch", { repository }),
  gitPull: (repository: string) => invoke<GitStatusDto>("git_pull", { repository }),
  gitPush: (repository: string) => invoke<GitStatusDto>("git_push", { repository }),
  gitSetOrigin: (repository: string, remote: string) => invoke<GitStatusDto>("git_set_origin", { repository, remote }),
  gitSetIdentity: (repository: string, name: string, email: string) => invoke<OperationDto>("git_set_identity", { repository, name, email }),
  listBackups: (repository: string) => invoke<BackupDto[]>("backups_list", { repository }),
  restoreBackup: (repository: string, id: string) => invoke<OperationDto>("backup_restore", { repository, id }),
};
